### ISSUE TITLE
Change CI to build from distribution tarball

### ISSUE THREAD

**Issue by ultimaweapon** [trustedvote/trustedvote#15]

**Comment by Sinderella** [comment]
Not sure if I understand this issue fully. So you would rather have it build a tarball from tag rather than from the repository itself?
Wouldn't the CI already build them separately in each commit?

**Comment by ultimaweapon** [comment]
คือตอนนี้มัน build จาก source ที่อยู่ใน root ของ repository เลยครับ ปัญหาของวิธีนี้คือเวลาเราจะสร้าง distribution tarball ไฟล์มันอาจจะไปไม่ครบ

สเตปคร่าว ๆ คือหลังจาก `./configure` เสร็จ `make dist` แล้วแตกไฟล์ที่ได้แล้วเข้าไป build ในนั้นแทนครับ

**Comment by Sinderella** [comment]
Something like the #29? I am still a bit lost. haha
